import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const backendDir = join(scriptDir, "..");
const outputPath = join(backendDir, "src", "db", "current-schema.sql");
const temporaryDir = mkdtempSync(join(tmpdir(), "efh-schema-"));
process.env.DB_PATH = join(temporaryDir, "schema.db");

try {
  const { getDb, closeDb } = await import("../src/db/index.js");
  const database = getDb();
  const rows = database.prepare(`
    SELECT type, name, tbl_name, sql
    FROM sqlite_master
    WHERE name NOT LIKE 'sqlite_%' AND sql IS NOT NULL
    ORDER BY CASE type WHEN 'table' THEN 1 WHEN 'index' THEN 2 WHEN 'view' THEN 3 WHEN 'trigger' THEN 4 ELSE 5 END,
             name
  `).all() as Array<{ type: string; name: string; tbl_name: string; sql: string }>;
  const migrations = database.prepare("SELECT id, applied_at FROM _migrations ORDER BY id").all() as Array<{ id: string; applied_at: string }>;
  const generated = [
    "-- Enterprise Flow Hub: current complete SQLite schema snapshot.",
    "-- Generated by: pnpm --filter backend schema:snapshot",
    "-- Source of truth for changes remains src/db/schema.sql + src/db/migrations/*.sql.",
    `-- Applied migration files: ${migrations.length}`,
    "-- Database foreign keys are intentionally absent; logical relations are documented in docs/current-schema.md.",
    "",
    ...rows.flatMap((row) => [
      `-- ${row.type}: ${row.name}${row.tbl_name !== row.name ? ` (on ${row.tbl_name})` : ""}`,
      `${row.sql.replace(/;\s*$/, "")};`,
      "",
    ]),
  ].join("\n");
  closeDb();

  if (process.argv.includes("--check")) {
    const existing = readFileSync(outputPath, "utf8");
    if (existing !== generated) {
      console.error("current-schema.sql is stale. Run pnpm --filter backend schema:snapshot");
      process.exitCode = 1;
    } else {
      console.log(`Schema snapshot is current (${rows.length} objects, ${migrations.length} migrations).`);
    }
  } else {
    writeFileSync(outputPath, generated);
    console.log(`Wrote ${outputPath} (${rows.length} objects, ${migrations.length} migrations).`);
  }
} finally {
  rmSync(temporaryDir, { recursive: true, force: true });
}
