-- Enterprise Flow Hub: current complete SQLite schema snapshot.
-- Generated by: pnpm --filter backend schema:snapshot
-- Source of truth for changes remains src/db/schema.sql + src/db/migrations/*.sql.
-- Applied migration files: 25
-- Database foreign keys are intentionally absent; logical relations are documented in docs/current-schema.md.

-- table: _migrations
CREATE TABLE _migrations (
        id         TEXT PRIMARY KEY,
        applied_at TEXT NOT NULL DEFAULT (datetime('now'))
      );

-- table: agent_model_configs
CREATE TABLE agent_model_configs (
  id                    TEXT PRIMARY KEY,
  name                  TEXT NOT NULL,
  thinking_provider_id  TEXT NOT NULL,
  executor_provider_id  TEXT NOT NULL,
  embedding_provider_id TEXT NOT NULL,
  active                INTEGER NOT NULL DEFAULT 0 CHECK (active IN (0, 1)),
  created_at            TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: agent_personas
CREATE TABLE agent_personas (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL,
  role              TEXT NOT NULL,
  description       TEXT NOT NULL DEFAULT '',
  system_prompt     TEXT NOT NULL DEFAULT '',
  default_skill_ids TEXT NOT NULL DEFAULT '[]',
  provider_id       TEXT NOT NULL DEFAULT 'provider-deepseek',
  enabled           INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))
, thinking_provider_id TEXT, memory TEXT DEFAULT '');

-- table: agent_skills
CREATE TABLE agent_skills (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  tool_ids    TEXT NOT NULL DEFAULT '[]',
  prompt      TEXT NOT NULL DEFAULT '',
  enabled     INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  created_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: ai_tools
CREATE TABLE ai_tools (
  id             TEXT PRIMARY KEY,
  name           TEXT NOT NULL,
  description    TEXT NOT NULL DEFAULT '',
  kind           TEXT NOT NULL CHECK (kind IN ('mcp','cli','http','browser')),
  status         TEXT NOT NULL DEFAULT 'needs_config' CHECK (status IN ('enabled','needs_config','disabled')),
  risk           TEXT NOT NULL DEFAULT 'read_only' CHECK (risk IN ('read_only','write','admin')),
  input_schema   TEXT NOT NULL DEFAULT '{}',
  example_prompt TEXT NOT NULL DEFAULT '',
  created_at     TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: analysis_results
CREATE TABLE analysis_results (
  id                  TEXT PRIMARY KEY,
  summary             TEXT NOT NULL,
  screenshot_types    TEXT NOT NULL DEFAULT '[]',
  business_objects    TEXT NOT NULL DEFAULT '[]',
  fields              TEXT NOT NULL DEFAULT '[]',
  workflow_stages     TEXT NOT NULL DEFAULT '[]',
  problems            TEXT NOT NULL DEFAULT '[]',
  automation_rules    TEXT NOT NULL DEFAULT '[]',
  dashboard_metrics   TEXT NOT NULL DEFAULT '[]',
  implementation_plan TEXT NOT NULL DEFAULT '[]',
  created_at          TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: approvals
CREATE TABLE approvals (
  id              TEXT PRIMARY KEY,
  enterprise_id   TEXT NOT NULL,
  requestor_id    TEXT,
  approver_id     TEXT,
  object_type     TEXT NOT NULL,
  object_id       TEXT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected','cancelled')),
  comment         TEXT NOT NULL DEFAULT '',
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  resolved_at     TEXT
);

-- table: audit_logs
CREATE TABLE audit_logs (
  id              TEXT PRIMARY KEY,
  enterprise_id   TEXT NOT NULL,
  user_id         TEXT,
  action          TEXT NOT NULL,
  object_type     TEXT NOT NULL,
  object_id       TEXT,
  changes         TEXT NOT NULL DEFAULT '{}',
  ip_address      TEXT NOT NULL DEFAULT '',
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: automation_jobs
CREATE TABLE automation_jobs (
  id               TEXT PRIMARY KEY,
  automation_id    TEXT NOT NULL,
  trigger_source   TEXT NOT NULL,
  trigger_event    TEXT NOT NULL DEFAULT '{}',
  dedupe_key       TEXT NOT NULL UNIQUE,
  status           TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','running','success','failed','dead')),
  attempts         INTEGER NOT NULL DEFAULT 0,
  max_attempts     INTEGER NOT NULL DEFAULT 3,
  available_at     TEXT NOT NULL,
  lease_owner      TEXT,
  lease_expires_at TEXT,
  output           TEXT NOT NULL DEFAULT '',
  error_message    TEXT NOT NULL DEFAULT '',
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL,
  started_at       TEXT,
  completed_at     TEXT
);

-- table: automation_leases
CREATE TABLE automation_leases (
  automation_id    TEXT PRIMARY KEY,
  owner_id         TEXT NOT NULL,
  acquired_at      TEXT NOT NULL,
  heartbeat_at     TEXT NOT NULL,
  lease_expires_at TEXT NOT NULL
);

-- table: automation_runs
CREATE TABLE automation_runs (
  id            TEXT PRIMARY KEY,
  automation_id TEXT NOT NULL,
  status        TEXT NOT NULL CHECK (status IN ('success','error')),
  trigger_event TEXT NOT NULL DEFAULT '{}',
  output        TEXT NOT NULL DEFAULT '',
  error_message TEXT NOT NULL DEFAULT '',
  duration_ms   INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: automations
CREATE TABLE automations (
  id               TEXT PRIMARY KEY,
  project_id       TEXT NOT NULL,
  name             TEXT NOT NULL,
  trigger_desc     TEXT NOT NULL,
  trigger_type     TEXT NOT NULL CHECK (trigger_type IN ('schedule','message','webhook','email','file','manual')),
  action_desc      TEXT NOT NULL,
  action_type      TEXT NOT NULL CHECK (action_type IN ('send_email','call_ai','shell','api_call','notify','browser','tool_call')),
  agent_model      TEXT,
  action_plugin_id TEXT,
  action_tool_id   TEXT,
  action_input     TEXT NOT NULL DEFAULT '{}',
  workflow_graph   TEXT,
  system_prompt    TEXT,
  webhook_secret   TEXT,
  enabled          INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  run_count        INTEGER NOT NULL DEFAULT 0,
  last_run         TEXT,
  last_status      TEXT CHECK (last_status IN ('success','error')),
  last_output      TEXT,
  last_error       TEXT,
  last_duration_ms INTEGER
);

-- table: business_event_deliveries
CREATE TABLE business_event_deliveries (
  event_id         TEXT NOT NULL,
  handler_key      TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','running','success','failed','dead')),
  attempts         INTEGER NOT NULL DEFAULT 0,
  max_attempts     INTEGER NOT NULL DEFAULT 5,
  available_at     TEXT NOT NULL,
  lease_owner      TEXT,
  lease_expires_at TEXT,
  last_error       TEXT NOT NULL DEFAULT '',
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL,
  completed_at     TEXT,
  PRIMARY KEY (event_id, handler_key)
);

-- table: business_events
CREATE TABLE business_events (
  id            TEXT PRIMARY KEY,
  event_type    TEXT NOT NULL,
  object_type   TEXT,
  object_id     TEXT,
  payload       TEXT NOT NULL DEFAULT '{}',
  source        TEXT NOT NULL DEFAULT 'system',
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  processed     INTEGER NOT NULL DEFAULT 0 CHECK (processed IN (0, 1))
, dispatch_status TEXT NOT NULL DEFAULT 'pending'
  CHECK (dispatch_status IN ('pending','processing','success','failed','dead')), attempt_count INTEGER NOT NULL DEFAULT 0, max_attempts INTEGER NOT NULL DEFAULT 5, available_at TEXT, lease_owner TEXT, lease_expires_at TEXT, last_error TEXT NOT NULL DEFAULT '', processed_at TEXT);

-- table: business_object_statuses
CREATE TABLE business_object_statuses (
  id              TEXT PRIMARY KEY,
  object_type     TEXT NOT NULL,
  object_id       TEXT NOT NULL,
  status          TEXT NOT NULL,
  previous_status TEXT,
  changed_by      TEXT,
  changed_at      TEXT NOT NULL DEFAULT (datetime('now')),
  comment         TEXT NOT NULL DEFAULT ''
);

-- table: conversations
CREATE TABLE conversations (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  project_id    TEXT NOT NULL,
  title         TEXT NOT NULL,
  tags          TEXT NOT NULL DEFAULT '[]',
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
, scope_enterprise_ids TEXT NOT NULL DEFAULT '[]', scope_project_ids TEXT NOT NULL DEFAULT '[]', persona_id TEXT);

-- table: customers
CREATE TABLE customers (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  name          TEXT NOT NULL,
  contact       TEXT NOT NULL DEFAULT '',
  phone         TEXT NOT NULL DEFAULT '',
  email         TEXT NOT NULL DEFAULT '',
  address       TEXT NOT NULL DEFAULT '',
  tags          TEXT NOT NULL DEFAULT '[]',
  status        TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active','inactive','lead','lost')),
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
, gender TEXT NOT NULL DEFAULT 'unknown'
  CHECK (gender IN ('unknown','male','female','other')), project_id TEXT);

-- table: departments
CREATE TABLE departments (
        id            TEXT PRIMARY KEY,
        enterprise_id TEXT NOT NULL,
        parent_id     TEXT,
        name          TEXT NOT NULL,
        created_at    TEXT NOT NULL DEFAULT (datetime('now'))
      );

-- table: enterprises
CREATE TABLE enterprises (
  id         TEXT PRIMARY KEY,
  name       TEXT NOT NULL
, tags TEXT NOT NULL DEFAULT '[]');

-- table: files
CREATE TABLE files (
  id              TEXT PRIMARY KEY,
  enterprise_id   TEXT NOT NULL,
  filename        TEXT NOT NULL,
  mime_type       TEXT NOT NULL,
  size            INTEGER NOT NULL DEFAULT 0,
  storage_path    TEXT NOT NULL,
  uploaded_by     TEXT,
  related_type    TEXT,
  related_id      TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
, project_id TEXT);

-- table: integration_runs
CREATE TABLE integration_runs (
  id                TEXT PRIMARY KEY,
  integration_type  TEXT NOT NULL,
  object_type       TEXT,
  object_id         TEXT,
  status            TEXT NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','running','success','failed','cancelled')),
  request_payload   TEXT NOT NULL DEFAULT '{}',
  response_payload  TEXT NOT NULL DEFAULT '',
  error_message     TEXT NOT NULL DEFAULT '',
  retry_count       INTEGER NOT NULL DEFAULT 0,
  max_retries       INTEGER NOT NULL DEFAULT 3,
  next_retry_at     TEXT,
  idempotency_key   TEXT UNIQUE,
  created_at        TEXT NOT NULL DEFAULT (datetime('now')),
  completed_at      TEXT
, lease_owner TEXT, lease_expires_at TEXT, heartbeat_at TEXT);

-- table: invoices
CREATE TABLE invoices (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  order_id      TEXT,
  customer_id   TEXT,
  amount        REAL NOT NULL,
  status        TEXT NOT NULL DEFAULT 'draft'
                CHECK (status IN ('draft','issued','paid','overdue','cancelled')),
  due_date      TEXT,
  issued_at     TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
, invoice_number TEXT, invoice_code TEXT, invoice_type TEXT, tax_rate REAL, tax_amount REAL, total_amount REAL, buyer_name TEXT, buyer_tax_id TEXT, seller_name TEXT, seller_tax_id TEXT, remark TEXT, issuer TEXT, source_file_id TEXT, project_id TEXT);

-- table: library_items
CREATE TABLE library_items (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  project_id    TEXT NOT NULL,
  name          TEXT NOT NULL,
  type          TEXT NOT NULL CHECK (type IN ('screenshot', 'spreadsheet', 'document', 'note')),
  summary       TEXT NOT NULL,
  visibility    TEXT NOT NULL DEFAULT 'public' CHECK (visibility IN ('public', 'private')),
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: maintenance_runs
CREATE TABLE maintenance_runs (
  task_name        TEXT NOT NULL,
  schedule_slot    TEXT NOT NULL,
  status           TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending','running','success','failed','dead')),
  attempts         INTEGER NOT NULL DEFAULT 0,
  max_attempts     INTEGER NOT NULL DEFAULT 3,
  available_at     TEXT NOT NULL,
  lease_owner      TEXT,
  lease_expires_at TEXT,
  error_message    TEXT NOT NULL DEFAULT '',
  created_at       TEXT NOT NULL,
  updated_at       TEXT NOT NULL,
  completed_at     TEXT,
  PRIMARY KEY (task_name, schedule_slot)
);

-- table: messages
CREATE TABLE messages (
  id              TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  role            TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
  content         TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: model_providers
CREATE TABLE model_providers (
  id              TEXT PRIMARY KEY,
  name            TEXT NOT NULL,
  base_url        TEXT NOT NULL,
  model           TEXT NOT NULL,
  api_key_env     TEXT NOT NULL,
  enabled         INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))
, embedding_base_url TEXT NOT NULL DEFAULT '', embedding_model TEXT NOT NULL DEFAULT '', embedding_api_key TEXT NOT NULL DEFAULT '', provider_type TEXT NOT NULL DEFAULT 'chat'
  CHECK (provider_type IN ('chat', 'embedding')));

-- table: order_items
CREATE TABLE order_items (
  id          TEXT PRIMARY KEY,
  order_id    TEXT NOT NULL,
  product_id  TEXT,
  quantity    REAL NOT NULL DEFAULT 1,
  unit_price  REAL NOT NULL DEFAULT 0,
  subtotal    REAL NOT NULL DEFAULT 0
);

-- table: orders
CREATE TABLE orders (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  customer_id   TEXT,
  status        TEXT NOT NULL DEFAULT 'draft'
                CHECK (status IN ('draft','confirmed','processing','shipped','delivered','cancelled','refunded')),
  total_amount  REAL NOT NULL DEFAULT 0,
  notes         TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
, project_id TEXT);

-- table: payments
CREATE TABLE payments (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  order_id      TEXT,
  amount        REAL NOT NULL,
  method        TEXT NOT NULL DEFAULT 'cash'
                CHECK (method IN ('cash','bank_transfer','alipay','wechat','credit_card','other')),
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','completed','failed','refunded')),
  received_at   TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
, project_id TEXT);

-- table: plugin_configs
CREATE TABLE plugin_configs (
  plugin_id   TEXT PRIMARY KEY,
  config_json TEXT NOT NULL DEFAULT '{}',
  updated_at  TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: plugins
CREATE TABLE plugins (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  enabled     INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1))
);

-- table: products
CREATE TABLE products (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  name          TEXT NOT NULL,
  sku           TEXT NOT NULL DEFAULT '',
  category      TEXT NOT NULL DEFAULT '',
  unit_price    REAL NOT NULL DEFAULT 0,
  unit          TEXT NOT NULL DEFAULT '个',
  description   TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
, project_id TEXT);

-- table: projects
CREATE TABLE projects (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  name          TEXT NOT NULL,
  description   TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: rule_event_runs
CREATE TABLE rule_event_runs (
  event_id      TEXT NOT NULL,
  rule_id       TEXT NOT NULL,
  status        TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','success','failed')),
  attempts      INTEGER NOT NULL DEFAULT 0,
  error_message TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL,
  completed_at  TEXT,
  PRIMARY KEY (event_id, rule_id)
);

-- table: rules
CREATE TABLE rules (
  id              TEXT PRIMARY KEY,
  enterprise_id   TEXT NOT NULL,
  name            TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  object_type     TEXT NOT NULL,
  trigger_event   TEXT NOT NULL,
  condition_expr  TEXT NOT NULL DEFAULT '{}',
  action_type     TEXT NOT NULL
                  CHECK (action_type IN ('notify','set_field','create_task','trigger_approval','trigger_automation')),
  action_config   TEXT NOT NULL DEFAULT '{}',
  enabled         INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: sessions
CREATE TABLE sessions (
  id              TEXT PRIMARY KEY,
  user_id         TEXT NOT NULL,
  token           TEXT NOT NULL UNIQUE,
  expires_at      TEXT NOT NULL,
  created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: suppliers
CREATE TABLE suppliers (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  name          TEXT NOT NULL,
  contact       TEXT NOT NULL DEFAULT '',
  phone         TEXT NOT NULL DEFAULT '',
  email         TEXT NOT NULL DEFAULT '',
  address       TEXT NOT NULL DEFAULT '',
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
, tags TEXT NOT NULL DEFAULT '[]', project_id TEXT);

-- table: tasks
CREATE TABLE tasks (
  id              TEXT PRIMARY KEY,
  enterprise_id   TEXT NOT NULL,
  assignee_id     TEXT,
  title           TEXT NOT NULL,
  description     TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','in_progress','completed','cancelled')),
  priority        TEXT NOT NULL DEFAULT 'medium'
                  CHECK (priority IN ('low','medium','high','urgent')),
  due_date        TEXT,
  source_type     TEXT,
  source_id       TEXT,
  created_at      TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
, project_id TEXT);

-- table: tool_runs
CREATE TABLE tool_runs (
  id         TEXT PRIMARY KEY,
  tool_id    TEXT NOT NULL,
  status     TEXT NOT NULL CHECK (status IN ('success','error')),
  input      TEXT NOT NULL DEFAULT '{}',
  output     TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- table: users
CREATE TABLE users (
  id            TEXT PRIMARY KEY,
  enterprise_id TEXT NOT NULL,
  username      TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  display_name  TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'member' CHECK (role IN ('admin', 'member')),
  created_at    TEXT NOT NULL DEFAULT (datetime('now'))
, department_id TEXT, position TEXT DEFAULT '');

-- index: idx_agent_model_configs_active (on agent_model_configs)
CREATE INDEX idx_agent_model_configs_active
  ON agent_model_configs(active);

-- index: idx_agent_skills_enabled (on agent_skills)
CREATE INDEX idx_agent_skills_enabled      ON agent_skills(enabled);

-- index: idx_approvals_approver (on approvals)
CREATE INDEX idx_approvals_approver   ON approvals(approver_id);

-- index: idx_approvals_enterprise (on approvals)
CREATE INDEX idx_approvals_enterprise ON approvals(enterprise_id);

-- index: idx_approvals_object (on approvals)
CREATE INDEX idx_approvals_object     ON approvals(object_type, object_id);

-- index: idx_audit_enterprise (on audit_logs)
CREATE INDEX idx_audit_enterprise   ON audit_logs(enterprise_id);

-- index: idx_audit_object (on audit_logs)
CREATE INDEX idx_audit_object       ON audit_logs(object_type, object_id);

-- index: idx_audit_time (on audit_logs)
CREATE INDEX idx_audit_time         ON audit_logs(created_at);

-- index: idx_audit_user (on audit_logs)
CREATE INDEX idx_audit_user         ON audit_logs(user_id);

-- index: idx_automation_jobs_automation (on automation_jobs)
CREATE INDEX idx_automation_jobs_automation
  ON automation_jobs(automation_id, created_at DESC);

-- index: idx_automation_jobs_claim (on automation_jobs)
CREATE INDEX idx_automation_jobs_claim
  ON automation_jobs(status, available_at, lease_expires_at);

-- index: idx_automation_leases_expiry (on automation_leases)
CREATE INDEX idx_automation_leases_expiry
  ON automation_leases(lease_expires_at);

-- index: idx_automation_runs_automation (on automation_runs)
CREATE INDEX idx_automation_runs_automation ON automation_runs(automation_id, created_at DESC);

-- index: idx_automations_project (on automations)
CREATE INDEX idx_automations_project ON automations(project_id);

-- index: idx_bos_object (on business_object_statuses)
CREATE INDEX idx_bos_object ON business_object_statuses(object_type, object_id);

-- index: idx_bos_time (on business_object_statuses)
CREATE INDEX idx_bos_time   ON business_object_statuses(changed_at);

-- index: idx_business_events_dispatch (on business_events)
CREATE INDEX idx_business_events_dispatch
  ON business_events(processed, dispatch_status, available_at, lease_expires_at);

-- index: idx_conversations_enterprise (on conversations)
CREATE INDEX idx_conversations_enterprise  ON conversations(enterprise_id);

-- index: idx_conversations_project (on conversations)
CREATE INDEX idx_conversations_project     ON conversations(project_id);

-- index: idx_customers_enterprise (on customers)
CREATE INDEX idx_customers_enterprise ON customers(enterprise_id);

-- index: idx_customers_project (on customers)
CREATE INDEX idx_customers_project ON customers(project_id);

-- index: idx_customers_status (on customers)
CREATE INDEX idx_customers_status     ON customers(status);

-- index: idx_event_deliveries_claim (on business_event_deliveries)
CREATE INDEX idx_event_deliveries_claim
  ON business_event_deliveries(status, available_at, lease_expires_at);

-- index: idx_events_object (on business_events)
CREATE INDEX idx_events_object    ON business_events(object_type, object_id);

-- index: idx_events_processed (on business_events)
CREATE INDEX idx_events_processed ON business_events(processed, created_at);

-- index: idx_events_type (on business_events)
CREATE INDEX idx_events_type      ON business_events(event_type);

-- index: idx_files_enterprise (on files)
CREATE INDEX idx_files_enterprise ON files(enterprise_id);

-- index: idx_files_project (on files)
CREATE INDEX idx_files_project ON files(project_id);

-- index: idx_files_related (on files)
CREATE INDEX idx_files_related    ON files(related_type, related_id);

-- index: idx_int_idempotent (on integration_runs)
CREATE INDEX idx_int_idempotent ON integration_runs(idempotency_key);

-- index: idx_int_lease (on integration_runs)
CREATE INDEX idx_int_lease ON integration_runs(status, lease_expires_at);

-- index: idx_int_retry (on integration_runs)
CREATE INDEX idx_int_retry     ON integration_runs(next_retry_at);

-- index: idx_int_status (on integration_runs)
CREATE INDEX idx_int_status    ON integration_runs(status);

-- index: idx_invoices_customer (on invoices)
CREATE INDEX idx_invoices_customer   ON invoices(customer_id);

-- index: idx_invoices_enterprise (on invoices)
CREATE INDEX idx_invoices_enterprise ON invoices(enterprise_id);

-- index: idx_invoices_order (on invoices)
CREATE INDEX idx_invoices_order      ON invoices(order_id);

-- index: idx_invoices_project (on invoices)
CREATE INDEX idx_invoices_project ON invoices(project_id);

-- index: idx_invoices_source_file (on invoices)
CREATE INDEX idx_invoices_source_file ON invoices(source_file_id);

-- index: idx_library_items_enterprise (on library_items)
CREATE INDEX idx_library_items_enterprise  ON library_items(enterprise_id);

-- index: idx_library_items_project (on library_items)
CREATE INDEX idx_library_items_project     ON library_items(project_id);

-- index: idx_maintenance_runs_claim (on maintenance_runs)
CREATE INDEX idx_maintenance_runs_claim
  ON maintenance_runs(status, available_at, lease_expires_at);

-- index: idx_messages_conversation (on messages)
CREATE INDEX idx_messages_conversation     ON messages(conversation_id);

-- index: idx_model_providers_type (on model_providers)
CREATE INDEX idx_model_providers_type
  ON model_providers(provider_type, enabled);

-- index: idx_order_items_order (on order_items)
CREATE INDEX idx_order_items_order   ON order_items(order_id);

-- index: idx_orders_customer (on orders)
CREATE INDEX idx_orders_customer     ON orders(customer_id);

-- index: idx_orders_enterprise (on orders)
CREATE INDEX idx_orders_enterprise   ON orders(enterprise_id);

-- index: idx_orders_project (on orders)
CREATE INDEX idx_orders_project ON orders(project_id);

-- index: idx_orders_status (on orders)
CREATE INDEX idx_orders_status       ON orders(status);

-- index: idx_payments_enterprise (on payments)
CREATE INDEX idx_payments_enterprise ON payments(enterprise_id);

-- index: idx_payments_order (on payments)
CREATE INDEX idx_payments_order      ON payments(order_id);

-- index: idx_payments_project (on payments)
CREATE INDEX idx_payments_project ON payments(project_id);

-- index: idx_products_category (on products)
CREATE INDEX idx_products_category    ON products(category);

-- index: idx_products_enterprise (on products)
CREATE INDEX idx_products_enterprise  ON products(enterprise_id);

-- index: idx_products_project (on products)
CREATE INDEX idx_products_project ON products(project_id);

-- index: idx_projects_enterprise (on projects)
CREATE INDEX idx_projects_enterprise      ON projects(enterprise_id);

-- index: idx_rule_event_runs_status (on rule_event_runs)
CREATE INDEX idx_rule_event_runs_status
  ON rule_event_runs(status, updated_at);

-- index: idx_rules_enabled (on rules)
CREATE INDEX idx_rules_enabled       ON rules(enabled);

-- index: idx_rules_enterprise (on rules)
CREATE INDEX idx_rules_enterprise    ON rules(enterprise_id);

-- index: idx_rules_object_type (on rules)
CREATE INDEX idx_rules_object_type   ON rules(object_type);

-- index: idx_sessions_expires (on sessions)
CREATE INDEX idx_sessions_expires   ON sessions(expires_at);

-- index: idx_sessions_token (on sessions)
CREATE INDEX idx_sessions_token     ON sessions(token);

-- index: idx_suppliers_enterprise (on suppliers)
CREATE INDEX idx_suppliers_enterprise ON suppliers(enterprise_id);

-- index: idx_suppliers_project (on suppliers)
CREATE INDEX idx_suppliers_project ON suppliers(project_id);

-- index: idx_tasks_assignee (on tasks)
CREATE INDEX idx_tasks_assignee      ON tasks(assignee_id);

-- index: idx_tasks_enterprise (on tasks)
CREATE INDEX idx_tasks_enterprise    ON tasks(enterprise_id);

-- index: idx_tasks_project (on tasks)
CREATE INDEX idx_tasks_project ON tasks(project_id);

-- index: idx_tasks_status (on tasks)
CREATE INDEX idx_tasks_status        ON tasks(status);

-- index: idx_tool_runs_created (on tool_runs)
CREATE INDEX idx_tool_runs_created         ON tool_runs(created_at);

-- index: idx_tool_runs_tool (on tool_runs)
CREATE INDEX idx_tool_runs_tool            ON tool_runs(tool_id);

-- index: idx_users_enterprise (on users)
CREATE INDEX idx_users_enterprise ON users(enterprise_id);

-- index: idx_users_username (on users)
CREATE INDEX idx_users_username  ON users(username);
